export const aboutTheme = {
  "/about": {
    container: "flex flex-col items-center gap-y-8",
    headerWrapper: "w-full text-center lg:w-full",
    title: "text-xl font-normal text-[#333333]",
    titleText: "Our accomplishment",
    showDesc: false,
    statsGrid: "grid grid-cols-3 my-[87px]",
    statItem: "pr-0 items-center",
    statValue: "text-[80px] font-normal text-[#333333]",
    statLabel: "text-md",
    imageContainer: "w-full h-[500px]",
    imageSrc: "/images/universities.jpg",
    projectsEnd: 100,
  },
  default: {
    container: "flex flex-col gap-16",
    headerWrapper: "text-start md:w-[61%] lg:w-full lg:flex-row",
    title: "text-4xl sm:text-5xl lg:text-4xl font-bold text-[#0097FE]",
    titleText: "About Us",
    showDesc: true,
    statsGrid: "grid grid-cols-3 mt-16",
    statItem: "pr-4 items-end border-r-1",
    statValue: "text-4xl font-normal text-[#333333]",
    statLabel: "text-sm",
    imageContainer: "w-full h-full lg:w-1/2",
    imageSrc: "/images/about.png",
    projectsEnd: 500,
  },
};
